version: "3.9"
services:
  finisher:
    build: finisher-service/.
    ports:
      - "5002:80"
    depends_on:
      - cache
    links:
      - "cache"
    environment:
      - "redis_connection=cache"
      
  cache:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    restart: unless-stopped      

volumes:
  cache:
    driver: local